var annotated_dup =
[
    [ "AmbientLight", "class_ambient_light.html", "class_ambient_light" ],
    [ "Camera", "class_camera.html", "class_camera" ],
    [ "ContextInfo", "struct_context_info.html", "struct_context_info" ],
    [ "DebugDrawer", "class_debug_drawer.html", "class_debug_drawer" ],
    [ "DirectionalLight", "class_directional_light.html", "class_directional_light" ],
    [ "DVertexFormat", "struct_d_vertex_format.html", "struct_d_vertex_format" ],
    [ "FrameBufferInfo", "struct_frame_buffer_info.html", "struct_frame_buffer_info" ],
    [ "GameObjectsBuilder", "class_game_objects_builder.html", "class_game_objects_builder" ],
    [ "IGameObject", "class_i_game_object.html", "class_i_game_object" ],
    [ "Init_GLEW", "class_init___g_l_e_w.html", "class_init___g_l_e_w" ],
    [ "Init_GLUT", "class_init___g_l_u_t.html", "class_init___g_l_u_t" ],
    [ "Light", "class_light.html", "class_light" ],
    [ "Material", "struct_material.html", null ],
    [ "Mesh", "class_mesh.html", "class_mesh" ],
    [ "Model", "class_model.html", "class_model" ],
    [ "Models_Manager", "class_models___manager.html", "class_models___manager" ],
    [ "Particle_Container", "class_particle___container.html", "class_particle___container" ],
    [ "Physics_Manager", "class_physics___manager.html", "class_physics___manager" ],
    [ "PointLight", "class_point_light.html", "class_point_light" ],
    [ "Scene_Container", "class_scene___container.html", "class_scene___container" ],
    [ "Scene_Manager", "class_scene___manager.html", "class_scene___manager" ],
    [ "Shader_Factory", "class_shader___factory.html", "class_shader___factory" ],
    [ "Shadow_Manager", "class_shadow___manager.html", "class_shadow___manager" ],
    [ "SpotLight", "class_spot_light.html", "class_spot_light" ],
    [ "Texture", "struct_texture.html", "struct_texture" ],
    [ "Transform", "class_transform.html", "class_transform" ],
    [ "VboIndexer", "class_vbo_indexer.html", null ],
    [ "VertexFormat", "struct_vertex_format.html", "struct_vertex_format" ],
    [ "WindowInfo", "struct_window_info.html", "struct_window_info" ]
];